### ISSUE TITLE
could not build the project

### ISSUE THREAD

**Issue by aatish-rajkarnikar** [evermeer/PassportScanner#20]
i downloaded the project and tried to build  but facing some difficulties. i am using Xcode 10. here is the screenshot of the error. 

<img width="1276" alt="screen shot 2018-10-08 at 2 00 02 pm" src="https://user-images.githubusercontent.com/19183428/46593041-1efc6d00-cb03-11e8-9e78-37309d70b900.png">

**Comment by aatish-rajkarnikar** [comment]
i was able to solve above issues by changing the swift language version to 4 in build setting. however another issue shows up. do you have any idea what i might be missing?

<img width="1280" alt="screen shot 2018-10-08 at 2 25 05 pm" src="https://user-images.githubusercontent.com/19183428/46593362-5f111f00-cb06-11e8-94fd-e1a1af25b00b.png">

**Comment by evermeer** [comment]
I just pushed an updated version to GitHub that builds again. The cocoapods publish is still running (can take 15 minutes)

**Comment by aatish-rajkarnikar** [comment]
Thank you for the response... i will check and let you know!! 👍

**Comment by evermeer** [comment]
Tip: When doing a pod update you will get a build error, you have to rename one of the 2 config_auto.h files (for instance to config_auto2.h) This is an issue with the Tesseract pod in Xcode 10

**Comment by aatish-rajkarnikar** [comment]
okay! i will keep note of that!

**Comment by aatish-rajkarnikar** [comment]
i did checked that branch too coz it is the only branch with a commit in an hour. and i can see that you switched from Tesseract to SwiftOCR which is completely fine but inside the project you are still using tesseract. so i still cannot build.

**Comment by evermeer** [comment]
the 'pod trunk push' failed without much details. 
I'm currently at work. Will try again this evening (now 3PM)

**Comment by punto2018** [comment]
Hi, I've tried with both xcode 9 and 10 and it fails when compiling.
Errors are the following:

<img width="679" alt="schermata 2018-10-09 alle 09 54 25" src="https://user-images.githubusercontent.com/32935246/46654530-5c1b3a80-cba9-11e8-90f6-ada5b464b8cf.png">

Any idea?
Thanks

**Comment by aatish-rajkarnikar** [comment]
@punto2018 i had the same issue and there were some spell mistakes like "h" missing in adaptiveTreshold, extra "b" in abbortScan and extra "l" in sucessfullScan. i still could not fix the override issue.

**Comment by evermeer** [comment]
@punto2018 @aatish-rajkarnikar Yes, these methods were corrected in GpuImage2 and are fixed on GitHub. But for some reason I'm not able to push it to cocoapods. Keep getting an error without additional info:

 ```
   ** BUILD FAILED **
    
   Testing with `xcodebuild`. 
 -> PassportScanner (2.2.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
```

**Comment by evermeer** [comment]
It appeared not to be a tesseract issue but an issue with the implementation of tesseract in the library TesseractOCRiOS. fortunately someone was able to fix that issue and published it as cocoa pod TesseractOCRSDKiOS. I was able to publish a new PasportScanner version 3.0.3
